# Generated by Django 5.1.6 on 2025-03-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_gender_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='assets/profile_pics/default-user.png', upload_to='assets/profile_pics'),
        ),
    ]
