# Generated by Django 5.1.6 on 2025-03-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile_pics/default-user.png', upload_to='media/profile_pics'),
        ),
    ]
