# Generated by Django 5.1.6 on 2025-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_to_complete_profile',
            field=models.BooleanField(default=True),
        ),
    ]
