# Generated by Django 5.1.2 on 2025-02-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Author',
            new_name='author',
        ),
    ]
